add github

diff --git a/.github/workflows/build-mediaencoder.yml b/.github/workflows/build-mediaencoder.yml
--- a/.github/workflows/build-mediaencoder.yml
+++ b/.github/workflows/build-mediaencoder.yml
@@ -24,9 +24,13 @@ jobs:
 
       - name: Debug FFmpeg pkg-config
         run: |
-          echo "PKG_CONFIG_PATH=$PKG_CONFIG_PATH"
-          ls "$PKG_CONFIG_PATH"
-          pkg-config --modversion libavcodec || echo "libavcodec not found"
+         echo "PKG_CONFIG_PATH=$PKG_CONFIG_PATH"
+         for p in $(echo $PKG_CONFIG_PATH | tr ":" "\n"); do
+           echo "Checking path: $p"
+           ls "$p" || echo "Directory $p not found"
+         done
+         pkg-config --modversion libavcodec || echo "libavcodec not found"
+
 
       - name: Create build directory
         run: mkdir -p build
